# Based on https://game.ci/docs/github/getting-started
name: Cache Example 

on:
  workflow_dispatch:
jobs:
  build:
    name: Cacher
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Setup cache-id
        uses: actions/cache@v2
        id: cache-id
        with:
          path: ${{ runner.temp }}/cache-directory-example
          key: ${{ runner.os }}-cache-hello-world-key-v1.0

      - name: Create/Use cache
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'cache-install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-directory-example
