
name: Checkstyle Example 

# Does not seem to work when it is on   workflow_dispatch:
on:
  #workflow_dispatch: this workflow fails when using workflow_dispatch
  push:
    paths:
      # this workflow will only run if a .java file is pushed.
      - '**.java'
jobs:
  checkstyle:
    name: Checkstyler
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Run Google Code Analysis Here  
        uses: dbelyaev/action-checkstyle@v0.1.1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check, github-pr-review].
          reporter: github-check
          # Change reporter level if you need [info,warning,error].
          # GitHub Status Check won't become failure with a warning.
          level: warning
          workdir: src/main
          
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          locale: "US"
          path: src/main
