
name: Checkstyle Manual Example 

on:
  workflow_dispatch:
jobs:
  build:
    name: CheckstylerM
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Cache checkstyle jar
        id: cache-checkstyle-jar
        uses: actions/cache@v2
        with:
          path: jardir
          key: ${{ runner.os }}-checkstyle
    - name: Generate checkstyle jar
      if: steps.cache-checkstyle-jar.outputs.cache-hit != 'true'
      run: |
        mkdir jardir
        cd jardir
        wget --quiet https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.42/checkstyle-8.42-all.jar
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get jar file for checkstyle
      run: | 
        java -jar checkstyle-8.42-all.jar -c /google_checks.xml src/main/java/edu/uwb/App.java 

